### ISSUE TITLE
run example fail

### ISSUE THREAD

**Issue by clonn** [muralikg/puppetcam#2]
OS: ubuntu 14.04
Node: v8.11.3

fail log:

```
(node:10399) UnhandledPromiseRejectionWarning: Error: Could not start Xvfb.
    at Xvfb.startSync (/home/test/puppetcam/node_modules/xvfb/index.js:84:17)
    at main (/home/test/puppetcam/export.js:20:10)
    at Object.<anonymous> (/home/test/puppetcam/export.js:45:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
(node:10399) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10399) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by clonn** [comment]
have to 

```
sudo apt-get install xvfb  -y
```

**Comment by muralikg** [comment]
Yes, you are right. Had just mentioned it as dependency but did not include the command to install in the readme as it would be different for each OS.

**Comment by clonn** [comment]
But still with problem,

```
/puppetcam/node_modules/puppeteer/.local-chromium/linux-571375/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

```

**Comment by clonn** [comment]
looks puppetteer, that is required dependency libs in different OS,
In ubuntu,

```
sudo apt-get install xvfb  -y
sudo apt-get install libatk-bridge2.0-0
sudo apt-get install libgtk-3.0
```


ref,
https://github.com/GoogleChrome/puppeteer/issues/1598
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch
