### ISSUE TITLE
Errors when executing `npm install`

### ISSUE THREAD

**Issue by jzvi12** [muralikg/puppetcam#21]
Tried to install on Ubuntu 18.04 headless server

```
$ npm install

> sleep@3.0.1 install /home/ubuntu/puppetcam/node_modules/sleep
> node-gyp rebuild

make: Entering directory '/home/ubuntu/puppetcam/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
In file included from ../../nan/nan_converters.h:67:0,
                 from ../../nan/nan.h:202,
                 from ../sleep.cc:2:
../../nan/nan_converters_43_inl.h: In static member function â€˜static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)â€™:
../../nan/nan_converters_43_inl.h:18:51: error: no matching function for call to â€˜v8::Value::ToBoolean(v8::Local<v8::Context>)â€™
       val->To ## TYPE(isolate->GetCurrentContext())                            \
                                                   ^
../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro â€˜Xâ€™
 X(Boolean)
 ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:2845:18: note: candidate: v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate*) const
   Local<Boolean> ToBoolean(Isolate* isolate) const;
                  ^~~~~~~~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:2845:18: note:   no known conversion for argument 1 from â€˜v8::Local<v8::Context>â€™ to â€˜v8::Isolate*â€™
In file included from ../../nan/nan_converters.h:67:0,
                 from ../../nan/nan.h:202,
                 from ../sleep.cc:2:
../../nan/nan_converters_43_inl.h: In static member function â€˜static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)â€™:
../../nan/nan_converters_43_inl.h:37:57: error: no matching function for call to â€˜v8::Value::BooleanValue(v8::Local<v8::Context>)â€™
   return val->NAME ## Value(isolate->GetCurrentContext());                     \
                                                         ^
../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro â€˜Xâ€™
 X(bool, Boolean)
 ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:2855:8: note: candidate: bool v8::Value::BooleanValue(v8::Isolate*) const
   bool BooleanValue(Isolate* isolate) const;
        ^~~~~~~~~~~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:2855:8: note:   no known conversion for argument 1 from â€˜v8::Local<v8::Context>â€™ to â€˜v8::Isolate*â€™
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:203,
                 from ../sleep.cc:2:
../../nan/nan_implementation_12_inl.h: In static member function â€˜static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)â€™:
../../nan/nan_implementation_12_inl.h:105:32: error: no matching function for call to â€˜v8::Function::New(v8::Isolate*&, void (&)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Object>&)â€™
                           , obj));
                                ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:4407:31: note: candidate: static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)
   static MaybeLocal<Function> New(
                               ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:4407:31: note:   no known conversion for argument 1 from â€˜v8::Isolate*â€™ to â€˜v8::Local<v8::Context>â€™
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:203,
                 from ../sleep.cc:2:
../../nan/nan_implementation_12_inl.h: In static member function â€˜static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)â€™:
../../nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to â€˜v8::StringObject::New(v8::Local<v8::String>&)â€™
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:5784:23: note: candidate: static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)
   static Local<Value> New(Isolate* isolate, Local<String> value);
                       ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:5784:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:203,
                 from ../sleep.cc:2:
../../nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before â€˜>â€™ token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                          ^
../../nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before â€˜)â€™ token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                            ^
In file included from ../sleep.cc:2:0:
../../nan/nan.h: In constructor â€˜Nan::Utf8String::Utf8String(v8::Local<v8::Value>)â€™:
../../nan/nan.h:1034:53: error: no matching function for call to â€˜v8::Value::ToString()â€™
       v8::Local<v8::String> string = from->ToString();
                                                     ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:2807:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^~~~~~~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:2807:44: note:   candidate expects 1 argument, 0 provided
In file included from ../sleep.cc:2:0:
../../nan/nan.h:1044:74: error: no matching function for call to â€˜v8::String::WriteUtf8(char*&, int, int, const int&)â€™
         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                                                          ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3034:7: note: candidate: int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3034:7: note:   no known conversion for argument 1 from â€˜char*â€™ to â€˜v8::Isolate*â€™
In file included from ../sleep.cc:2:0:
../../nan/nan.h: In member function â€˜void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)â€™:
../../nan/nan.h:1818:64: error: no matching function for call to â€˜v8::Object::Set(v8::Local<v8::String>, const v8::Local<v8::Value>&)â€™
     New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                                                                ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3639:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3642:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../sleep.cc:2:0:
../../nan/nan.h: In member function â€˜void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)â€™:
../../nan/nan.h:1824:42: error: no matching function for call to â€˜v8::Object::Set(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)â€™
     New(persistentHandle)->Set(key, value);
                                          ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3639:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3642:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../sleep.cc:2:0:
../../nan/nan.h: In member function â€˜void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value>&)â€™:
../../nan/nan.h:1830:44: error: no matching function for call to â€˜v8::Object::Set(uint32_t&, const v8::Local<v8::Value>&)â€™
     New(persistentHandle)->Set(index, value);
                                            ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3639:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3642:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../sleep.cc:2:0:
../../nan/nan.h: In member function â€˜v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) constâ€™:
../../nan/nan.h:1836:61: error: no matching function for call to â€˜v8::Object::Get(v8::Local<v8::String>)â€™
         New(persistentHandle)->Get(New(key).ToLocalChecked()));
                                                             ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3686:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3686:43: note:   candidate expects 2 arguments, 1 provided
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3689:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3689:43: note:   candidate expects 2 arguments, 1 provided
In file included from ../sleep.cc:2:0:
../../nan/nan.h: In member function â€˜v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String>&) constâ€™:
../../nan/nan.h:1842:55: error: no matching function for call to â€˜v8::Object::Get(const v8::Local<v8::String>&)â€™
     return scope.Escape(New(persistentHandle)->Get(key));
                                                       ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3686:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3686:43: note:   candidate expects 2 arguments, 1 provided
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3689:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3689:43: note:   candidate expects 2 arguments, 1 provided
In file included from ../sleep.cc:2:0:
../../nan/nan.h: In member function â€˜v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(uint32_t) constâ€™:
../../nan/nan.h:1847:57: error: no matching function for call to â€˜v8::Object::Get(uint32_t&)â€™
     return scope.Escape(New(persistentHandle)->Get(index));
                                                         ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3686:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3686:43: note:   candidate expects 2 arguments, 1 provided
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3689:43: note: candidate: v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:3689:43: note:   candidate expects 2 arguments, 1 provided
In file included from /usr/include/c++/7/cassert:44:0,
                 from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:53,
                 from ../sleep.cc:2:
../../nan/nan_object_wrap.h: In destructor â€˜virtual Nan::ObjectWrap::~ObjectWrap()â€™:
../../nan/nan_object_wrap.h:24:25: error: â€˜class Nan::Persistent<v8::Object>â€™ has no member named â€˜IsNearDeathâ€™
     assert(persistent().IsNearDeath());
                         ^
In file included from ../../nan/nan.h:2657:0,
                 from ../sleep.cc:2:
../../nan/nan_object_wrap.h: In member function â€˜void Nan::ObjectWrap::MakeWeak()â€™:
../../nan/nan_object_wrap.h:67:18: error: â€˜class Nan::Persistent<v8::Object>â€™ has no member named â€˜MarkIndependentâ€™
     persistent().MarkIndependent();
                  ^~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/cassert:44:0,
                 from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:53,
                 from ../sleep.cc:2:
../../nan/nan_object_wrap.h: In static member function â€˜static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)â€™:
../../nan/nan_object_wrap.h:124:26: error: â€˜class Nan::Persistent<v8::Object>â€™ has no member named â€˜IsNearDeathâ€™
     assert(wrap->handle_.IsNearDeath());
                          ^
../sleep.cc: At global scope:
../sleep.cc:6:11: error: â€˜v8::Handleâ€™ has not been declared
 using v8::Handle;
           ^~~~~~
../sleep.cc: In function â€˜Nan::NAN_METHOD_RETURN_TYPE Sleep(Nan::NAN_METHOD_ARGS_TYPE)â€™:
../sleep.cc:42:30: error: no matching function for call to â€˜v8::Value::Uint32Value()â€™
   sleep(info[0]->Uint32Value());
                              ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:2863:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:2863:41: note:   candidate expects 1 argument, 0 provided
../sleep.cc: In function â€˜Nan::NAN_METHOD_RETURN_TYPE USleep(Nan::NAN_METHOD_ARGS_TYPE)â€™:
../sleep.cc:54:31: error: no matching function for call to â€˜v8::Value::Uint32Value()â€™
   usleep(info[0]->Uint32Value());
                               ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:2863:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:2863:41: note:   candidate expects 1 argument, 0 provided
../sleep.cc: In function â€˜void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)â€™:
../sleep.cc:62:52: error: no matching function for call to â€˜v8::FunctionTemplate::GetFunction()â€™
     Nan::New<FunctionTemplate>(Sleep)->GetFunction());
                                                    ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:6404:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:6404:46: note:   candidate expects 1 argument, 0 provided
../sleep.cc:64:53: error: no matching function for call to â€˜v8::FunctionTemplate::GetFunction()â€™
     Nan::New<FunctionTemplate>(USleep)->GetFunction());
                                                     ^
In file included from /home/ubuntu/.cache/node-gyp/14.3.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:51,
                 from ../sleep.cc:2:
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:6404:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/ubuntu/.cache/node-gyp/14.3.0/include/node/v8.h:6404:46: note:   candidate expects 1 argument, 0 provided
node_sleep.target.mk:111: recipe for target 'Release/obj.target/node_sleep/sleep.o' failed
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
make: Leaving directory '/home/ubuntu/puppetcam/node_modules/sleep/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.0.0-1014-oracle
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/puppetcam/node_modules/sleep
gyp ERR! node -v v14.3.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> puppeteer@1.6.0 install /home/ubuntu/puppetcam/node_modules/puppeteer
> node install.js

Downloading Chromium r571375 - 101.4 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/ubuntu/puppetcam/node_modules/puppeteer/.local-chromium/linux-571375
npm WARN puppetcam@0.0.1 No repository field.
npm WARN puppetcam@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sleep@3.0.1 (node_modules/sleep):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sleep@3.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 42 packages from 22 contributors and audited 44 packages in 60.713s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
``

**Comment by muralikg** [comment]
Could be a problem with the node version you have. This was written with node-8
