### ISSUE TITLE
unable to run code

### ISSUE THREAD

**Issue by inglesuniversal** [muralikg/puppetcam#28]
error log on MacOS

    /Users/username/NodeJS/puppetcam/node_modules/xvfb/index.js:84
            throw new Error('Could not start Xvfb.');
                    ^

    Error: Could not start Xvfb.
        at Xvfb.startSync (/Users/username/NodeJS/puppetcam/node_modules/xvfb/index.js:84:17)
        at main (/Users/username/NodeJS/puppetcam/export.js:20:10)
        at Object.<anonymous> (/Users/username/NodeJS/puppetcam/export.js:45:1)
        at Module._compile (node:internal/modules/cjs/loader:1095:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
        at Module.load (node:internal/modules/cjs/loader:975:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        at node:internal/main/run_main_module:17:47

**Comment by inglesuniversal** [comment]
Hope you can give me a heads up on what could be wrong or missing...

Regards... Kool project!
